"""Authentication helpers for WeChat MP platform (微信公众平台) login."""

import logging
import time
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Iterator, Optional

from patchright.sync_api import Page, TimeoutError as PlaywrightTimeout, sync_playwright

from ...core.browser import get_state_path
from ...core.cookies import get_cookies_path
from .config import (
    BASE_URL,
    LOGIN_QR_SELECTOR,
    LOGIN_SUCCESS_INDICATOR,
    QR_IMAGE_PATH,
    SOURCE_NAME,
    Timeouts,
)

logger = logging.getLogger(__name__)


class LoginStatus(Enum):
    LOGGED_IN = "logged_in"
    LOGGED_OUT = "logged_out"
    UNKNOWN = "unknown"


@dataclass
class AuthStatus:
    status: LoginStatus
    checked_at: Optional[datetime] = None
    message: Optional[str] = None
    current_url: Optional[str] = None
    qr_image_path: Optional[str] = None


def _launch_strategies(headless: bool) -> list[tuple[str, dict]]:
    base_args = ["--disable-gpu", "--disable-blink-features=AutomationControlled"]
    return [
        ("chrome", {"headless": headless, "channel": "chrome", "args": base_args}),
        ("chromium", {"headless": headless, "args": base_args}),
    ]


@contextmanager
def _open_page(
    *,
    headless: bool,
    use_storage_state: bool,
) -> Iterator[Page]:
    """Create browser page with strategy fallback."""
    state_file = get_state_path(SOURCE_NAME)
    storage_state = str(state_file) if use_storage_state and state_file.exists() else None

    last_error: Optional[Exception] = None
    launched = False
    with sync_playwright() as playwright:
        for _name, launch_kwargs in _launch_strategies(headless):
            browser = None
            context = None
            try:
                browser = playwright.chromium.launch(**launch_kwargs)
                context_options = {
                    "viewport": {"width": 1440, "height": 1024},
                    "locale": "zh-CN",
                }
                if storage_state:
                    context_options["storage_state"] = storage_state

                context = browser.new_context(**context_options)
                context.add_init_script(
                    "Object.defineProperty(navigator, 'webdriver', { get: () => undefined });"
                )
                page = context.new_page()
                launched = True
            except Exception as exc:
                last_error = exc
                if context:
                    try:
                        context.close()
                    except Exception:
                        pass
                if browser:
                    try:
                        browser.close()
                    except Exception:
                        pass
                continue

            try:
                yield page
            finally:
                try:
                    context.close()
                finally:
                    browser.close()
            return

    if not launched:
        raise RuntimeError(f"Browser launch failed: {last_error}")


def _save_storage_state(page: Page) -> None:
    state_file = get_state_path(SOURCE_NAME)
    state_file.parent.mkdir(parents=True, exist_ok=True)
    page.context.storage_state(path=str(state_file))


def _save_cookies_txt(page: Page) -> Path:
    """Extract browser cookies and save as Netscape-format cookies.txt.

    This updates the same cookies.txt used by the HTTP-based scrapers
    (MPPlatformScraper, ArticleScraper), so login state is shared.
    """
    cookies_path = get_cookies_path(SOURCE_NAME)
    cookies_path.parent.mkdir(parents=True, exist_ok=True)

    browser_cookies = page.context.cookies()

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by scraper wechat login",
        "",
    ]
    for c in browser_cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = str(int(c.get("expires", 0)))
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")

    cookies_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Cookies saved to %s (%d entries)", cookies_path, len(browser_cookies))
    return cookies_path


def _capture_qr_code(page: Page, save_path: Path) -> Optional[str]:
    """Capture the login QR code image from the page.

    Returns the saved file path, or None if QR code not found.
    """
    save_path.parent.mkdir(parents=True, exist_ok=True)

    # Wait for QR code image to appear
    try:
        qr_el = page.wait_for_selector(LOGIN_QR_SELECTOR, timeout=10_000)
    except PlaywrightTimeout:
        logger.warning("QR code element not found within timeout")
        return None

    if not qr_el:
        return None

    # Wait for image to fully load (naturalWidth > 0)
    page.wait_for_function(
        f"""() => {{
            const img = document.querySelector('{LOGIN_QR_SELECTOR}');
            return img && img.naturalWidth > 0 && img.complete;
        }}""",
        timeout=10_000,
    )

    # Screenshot the QR code element
    qr_el.screenshot(path=str(save_path))
    logger.info("QR code saved to %s", save_path)
    return str(save_path)


def _is_logged_in(page: Page) -> bool:
    """Check if page shows logged-in state (MP dashboard)."""
    url = page.url
    # After login, URL changes to dashboard with token parameter
    if "/cgi-bin/home" in url and "token=" in url:
        return True
    # Or check for dashboard elements
    try:
        el = page.query_selector(LOGIN_SUCCESS_INDICATOR)
        if el and el.is_visible():
            return True
    except Exception:
        pass
    return False


def interactive_login(
    headless: bool = False,
    timeout_seconds: int = Timeouts.LOGIN_MANUAL // 1000,
    qr_save_path: Optional[Path] = None,
    on_qr_ready: Optional[callable] = None,
) -> AuthStatus:
    """Open WeChat MP login page, capture QR code, wait for scan.

    Args:
        headless: Run browser headlessly (QR image will be saved for scanning).
        timeout_seconds: Max wait time for user to scan QR code.
        qr_save_path: Where to save the QR code image. Defaults to QR_IMAGE_PATH.
        on_qr_ready: Callback invoked immediately after QR code is saved, with path as argument.
    """
    save_path = qr_save_path or QR_IMAGE_PATH
    page: Optional[Page] = None

    try:
        with _open_page(headless=headless, use_storage_state=False) as opened_page:
            page = opened_page
            page.goto(BASE_URL, wait_until="domcontentloaded", timeout=Timeouts.NAVIGATION)
            page.wait_for_timeout(2000)

            # Capture QR code
            qr_path = _capture_qr_code(page, save_path)
            if not qr_path:
                return AuthStatus(
                    status=LoginStatus.UNKNOWN,
                    checked_at=datetime.now(),
                    message="Failed to capture QR code from login page",
                    current_url=page.url,
                )

            # Notify caller immediately so they can display the path
            if on_qr_ready:
                on_qr_ready(qr_path)

            # Poll for login success
            start_time = time.time()
            while time.time() - start_time < timeout_seconds:
                if _is_logged_in(page):
                    _save_storage_state(page)
                    cookies_path = _save_cookies_txt(page)
                    n_cookies = len(page.context.cookies())
                    return AuthStatus(
                        status=LoginStatus.LOGGED_IN,
                        checked_at=datetime.now(),
                        message=f"Login successful, {n_cookies} cookies saved to {cookies_path}",
                        current_url=page.url,
                        qr_image_path=qr_path,
                    )
                page.wait_for_timeout(1500)

            return AuthStatus(
                status=LoginStatus.LOGGED_OUT,
                checked_at=datetime.now(),
                message="Login timeout - QR code not scanned in time",
                current_url=page.url,
                qr_image_path=qr_path,
            )

    except PlaywrightTimeout:
        return AuthStatus(
            status=LoginStatus.UNKNOWN,
            checked_at=datetime.now(),
            message="Timeout while opening login page",
            current_url=page.url if page else None,
        )
    except Exception as exc:
        return AuthStatus(
            status=LoginStatus.UNKNOWN,
            checked_at=datetime.now(),
            message=f"Login failed: {exc}",
            current_url=page.url if page else None,
        )


def check_saved_session(headless: bool = True) -> AuthStatus:
    """Validate saved storage state by opening MP platform."""
    state_file = get_state_path(SOURCE_NAME)
    if not state_file.exists():
        return AuthStatus(
            status=LoginStatus.LOGGED_OUT,
            checked_at=datetime.now(),
            message="No saved session. Run 'scraper wechat login' first.",
        )

    page: Optional[Page] = None
    try:
        with _open_page(headless=headless, use_storage_state=True) as opened_page:
            page = opened_page
            page.goto(BASE_URL, wait_until="domcontentloaded", timeout=Timeouts.NAVIGATION)
            page.wait_for_timeout(3000)

            if _is_logged_in(page):
                # Refresh cookies.txt with current browser cookies
                _save_cookies_txt(page)
                return AuthStatus(
                    status=LoginStatus.LOGGED_IN,
                    checked_at=datetime.now(),
                    message="Session is valid",
                    current_url=page.url,
                )

            return AuthStatus(
                status=LoginStatus.LOGGED_OUT,
                checked_at=datetime.now(),
                message="Session expired, please login again",
                current_url=page.url,
            )
    except Exception as exc:
        return AuthStatus(
            status=LoginStatus.UNKNOWN,
            checked_at=datetime.now(),
            message=f"Session check failed: {exc}",
            current_url=page.url if page else None,
        )


def clear_session() -> bool:
    """Delete saved session state file."""
    state_file = get_state_path(SOURCE_NAME)
    if state_file.exists():
        state_file.unlink()
        return True
    return False
