"""Authentication for Ctrip — Playwright interactive login + Netscape cookie export."""
import time
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Iterator, Optional

from patchright.sync_api import Page, TimeoutError as PlaywrightTimeout, sync_playwright
from rich.console import Console

from .config import SOURCE_NAME
from .cookies import get_cookies_path

console = Console()

LOGIN_URL = "https://passport.ctrip.com/user/login"
HOME_URL = "https://www.ctrip.com/"
LOGIN_TIMEOUT_SECONDS = 180  # 3 minutes for user to complete login


class LoginStatus(Enum):
    LOGGED_IN = "logged_in"
    LOGGED_OUT = "logged_out"
    UNKNOWN = "unknown"


@dataclass
class AuthStatus:
    status: LoginStatus
    message: str
    checked_at: Optional[datetime] = None


# ─────────────────────────────────────────
# Browser helpers
# ─────────────────────────────────────────

@contextmanager
def _open_page(*, headless: bool = False) -> Iterator[Page]:
    """Launch a Chrome browser and yield a Page, then close cleanly."""
    with sync_playwright() as pw:
        for launch_kwargs in [
            {"channel": "chrome", "headless": headless,
             "args": ["--disable-blink-features=AutomationControlled"]},
            {"headless": headless,
             "args": ["--disable-blink-features=AutomationControlled"]},
        ]:
            browser = None
            try:
                browser = pw.chromium.launch(**launch_kwargs)
                context = browser.new_context(
                    viewport={"width": 1440, "height": 900},
                    locale="zh-CN",
                )
                context.add_init_script(
                    "Object.defineProperty(navigator, 'webdriver', { get: () => undefined });"
                )
                page = context.new_page()
                try:
                    yield page
                finally:
                    try:
                        context.close()
                    finally:
                        browser.close()
                return
            except Exception:
                if browser:
                    try:
                        browser.close()
                    except Exception:
                        pass


def _has_cticket(page: Page) -> bool:
    """Return True if browser context has a valid cticket cookie."""
    try:
        cookies = page.context.cookies()
        for c in cookies:
            if c["name"] == "cticket" and c.get("value"):
                return True
    except Exception:
        pass
    return False


def _save_netscape_cookies(page: Page) -> None:
    """Export all browser cookies to Netscape format file."""
    dest = get_cookies_path()
    dest.parent.mkdir(parents=True, exist_ok=True)

    cookies = page.context.cookies()
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by WebScraper Ctrip login",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = int(c.get("expires", 0))
        if expires < 0:
            expires = 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}")

    dest.write_text("\n".join(lines), encoding="utf-8")
    console.print(f"[dim]Cookies 已保存至：{dest}[/dim]")


# ─────────────────────────────────────────
# Public API
# ─────────────────────────────────────────

def interactive_login(timeout_seconds: int = LOGIN_TIMEOUT_SECONDS) -> AuthStatus:
    """
    Open Ctrip login page and wait for user to complete login.

    Detects login by polling for the `cticket` cookie every second.
    On success, exports all cookies to Netscape format for httpx reuse.
    """
    console.print("[bold cyan]打开携程登录页，请在浏览器中完成登录…[/bold cyan]")
    console.print(f"[dim]支持：扫码 / 手机验证码 / 账号密码（超时 {timeout_seconds}s）[/dim]")

    try:
        with _open_page(headless=False) as page:
            page.goto(LOGIN_URL, wait_until="domcontentloaded", timeout=30000)
            page.wait_for_timeout(1500)

            start = time.time()
            while time.time() - start < timeout_seconds:
                if _has_cticket(page):
                    # Give page a moment to settle and set all cookies
                    page.wait_for_timeout(2000)
                    _save_netscape_cookies(page)
                    return AuthStatus(
                        status=LoginStatus.LOGGED_IN,
                        message="登录成功，cookies 已保存",
                        checked_at=datetime.now(),
                    )
                page.wait_for_timeout(1000)

            return AuthStatus(
                status=LoginStatus.LOGGED_OUT,
                message=f"等待超时（{timeout_seconds}s），请重试",
                checked_at=datetime.now(),
            )

    except PlaywrightTimeout:
        return AuthStatus(
            status=LoginStatus.UNKNOWN,
            message="打开登录页超时，请检查网络连接",
            checked_at=datetime.now(),
        )
    except Exception as e:
        msg = str(e)
        if "Executable doesn't exist" in msg:
            msg = "Patchright 浏览器未安装，请运行：patchright install chromium"
        elif "Target page" in msg and "closed" in msg:
            msg = "浏览器意外关闭，请重试"
        return AuthStatus(
            status=LoginStatus.UNKNOWN,
            message=msg,
            checked_at=datetime.now(),
        )


def clear_session() -> bool:
    """Delete saved cookies file."""
    path = get_cookies_path()
    if path.exists():
        path.unlink()
        return True
    return False
